# Generated by Django 2.1.5 on 2020-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('publish_date', models.DateTimeField()),
                ('blog_body', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
